accounts/urls.py
from django.urls import path

from .views import EmailVerification, home, signup_view, login_view, logout_view, successful_verification, verification_failed


urlpatterns = [
    path('signup', signup_view, name='signup'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('email_verification/<int:pk>', EmailVerification.as_view(), name='email_verification'),
    path('successful_verification', successful_verification, name='successful_verification'),
    path('verification_failed', verification_failed, name='verification_failed'),
    path('', home, name='home'),
]

classifiedads/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adsboard.urls')),
    path('', include('accounts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

adsboard/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse



class Category(models.Model):
    name = models.CharField(max_length=128, unique=True, help_text="Category name")

    def __str__(self):
        return self.name
    

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=128)
    content = RichTextField(blank=True, null=True)
    post_time = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory', related_name='categorys')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    @property
    def preview(self):
        words = self.content.split()
        preview_text = ' '.join(words[:20])
        if len(words) > 20:
            preview_text += '...'
        return preview_text


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    post_time = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering=['-post_time']

    def __str__(self):
        return 'Comment by {}'.format(self.author)
    
    def get_absolute_url(self):
        return f'{self.pk}'
    

class OTPCode(models.Model):
    code = models.BigIntegerField()
    related_user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

templates/commentapproval.html
{% extends 'default.html' %}

{% load i18n %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}

<div style="display: flex">
    <div style="flex-basis: 90%">
        <br>
        <h4>{%trans "Comments awaiting approval" %}</h4>
        <br>
        {% for comment in comments reversed %}
            {% if not comment.status %}
                {% if comment.author == request.user %}
                <h6 style="text-align: left" >Your comment <b>"{{ comment.content }}"</b> was sent for approval to <b>{{ comment.post.author}}.</b></h6>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
</div>

{% if 'posts' in request.path %}
<p align="center"><a href="{% url 'post_list' %}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 {%trans "Back to Posts" %}</a></p>
{% endif %}
{% endblock content %}

templates/createcomment.html
{% extends 'default.html' %}

{% load i18n %}
{% load static %}

{% block content %}
    <br>
    <h4>{% trans "Write your comment:" %}</h4><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
	    {{ form.as_p }}
		<input class="btn btn-secondary" type="submit" value="{% trans 'Send' %}">
	</form><br>
    <input type=button value="Back" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

templates/default.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% trans "Classified Ads Portal" %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>

<body id="bg" style="background-image: url('static/image/home-background.png');">

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">{% trans "Classified Ads Portal" %}</a>
        
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="navbar-nav me-auto">

                <li class="nav-item">
                    <a class="nav-link" href="/posts/">{% trans "Posts" %}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/search/">{% trans "Search" %}</a>
                </li>
                
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <form action="/posts/create/" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary">{% trans "Create a post" %}</button>
                    </form>
                    {% endif %}
                </li>
            </ul>
            
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link user-link">{{ request.user }}</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="/accounts/logout">{% trans "Sign Out" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/profile">{% trans "My Account" %}</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="/usercomments">User Comments</a>
                </li> -->

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/login">{% trans "Sign In" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/signup">{% trans "Sign Up" %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div>
            <!-- Выбор языка -->
                <form action="{% url 'set_language' %}" method="POST" style="display: inline-block;">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="">
                    {% get_current_language as LANGUAGE_CODE %}
                    <select name="language">
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}
                                    selected {% endif %}> {{ language.name_local }} - {{ language.code }}
                            </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="{% trans 'Set' %}">
                </form>
            </div>
    </nav>
    {% block content%}
    {% endblock %}



    <!-- Bootstrap JS and jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

templates/home.html
{% extends "default.html" %}

{% load static %}
{% load i18n %}

{% block title %}
{% trans "Home" %}
{% endblock title %}

{% block content %}
<style>
    #bg {background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: top;
        background-size: 1800px 1000px;
    }
</style>
{% if request.user.is_authenticated %}

<div class="text-center">
    <h2 class="text-center">{% trans "Welcome to Fan MMORPG" %}</h2>
    <h3 class="text-center">{% trans "Classified Ads Portal!" %}</h3>
</div>
  
{% else %}
<div class="login-prompt">
    <div class="text-center">
        <h2 class="text-center">{% trans "Welcome to Fan MMORPG" %}</h2>
        <h3 class="text-center">{% trans "Classified Ads Portal!" %}</h3>
        <p>{% trans "Please sign in or sign up to continue." %}</p>
        <div class="mt-4">
            <a href="/accounts/login" class="btn btn-primary mr-2">{% trans "Sign In" %}</a>
            <a href="/accounts/signup" class="btn btn-success">{% trans "Sign Up" %}</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/mypost_detail.html
{% extends 'default.html' %}

{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}

{% block title %}
{{ post.title|censor }}
{% endblock title %}

{% block content %}
<h1>{{ post.title|censor }}</h1>
<p class="card-text"><small class="text-muted">{{ post.post_time|format_time }} by {{ post.author }}
{% if user.is_authenticated and user == post.author %}
  <a href="{% url 'post_edit' post.id %}">Edit post /</a>
  <a href="{% url 'post_delete' post.id %}">Delete post</a>
{% endif %}
</small></p>
<p>{{ post.content|censor|safe }}</p>

<hr>
<h4>Comment{{ comments.count|pluralize }} ({{ comments.count }})</h4>
  {% for comment in comments reversed %}
    {% if comment.status %}
    <tr class="card-text">
        <td><i>{{ comment.author }} </i></td>
        <td><i>| {{ comment.post_time|format_time }} </i></td>
        {% if comment.author == request.user %}
                <i>| <a href="{% url 'comment_delete' comment.pk %}">Delete</a></i>
        {% endif %}
        <br>
        <td>{{ comment.content }}</td><br>

        <br><br>
    </tr>
    {% endif %}
  {% endfor %}

{% else %}
  No comments yet
{% endif %}

{% if 'myposts' in request.path %}
<p align="center"><a href="myposts/" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 {% trans "Back to My Posts" %}</a></p>
{%endif%}

{% if request.META.HTTP_REFERER %}
<p align="center"><a href="{{request.META.HTTP_REFERER}}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 {% trans "Back" %}</a></p>
{% endif %}

{% endblock content %}

templates/mypost_list.html
{% extends 'default.html' %}

{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}

{% block title %}
{% trans "My Posts" %}
{% endblock title  %}


{% block content %}
<h1 align="left" style="color: #000000"><b>{% trans "My Posts" %}</b></h1>
<hr>
<div align="left" class="form-group" style=" width: 800px">
    <div class="list-group" style="border-radius:10px; display: flex">
        <a class="list-group-item list-group-item list-group-item-warning" style="height: 50px; border-radius:10px">
            <div style="width:88%; float:left; font-weight:bold">
                <p>{% trans "My Posts" %} | {% trans "Total:" %} {% if posts_count%} {{posts_count}} {%endif%}</p>
            </div>
        </a>
        
        {% if MyPosts %}
            {% for post in MyPosts %}
                <a href="{% url 'mypost_detail' post.id %}" class="list-group-item list-group-item-action list-group-item-light">
                    <div style="width:90%;float: left;">

                        {{post.post_time|format_time}}
                        |
                        {{post.title}}
                        |
                        {{post.category.all.first.name}}
                    </div>

                </a>
            {%endfor%}
        {% else %}
            <a href="{% url 'post_create' %}" class="list-group-item list-group-item-action list-group-item-light">
                <div style="width:80%;float: left;">
                    {% trans "No posts yet." %}
                </div>
                <div style="width:20%; float:right">
                    <span class="btn btn-outline-warning" style="border-radius:10px">
                        {% trans "Create a post" %}
                    </span>
                </div>
            </a>
        {% endif %}
    </div>

    <a class="nav-link" href="/usercomments">User Comments for Approval</a>
</div>

{% endblock content %}

templates/pagination.html
{% load custom_tags %}
{% load i18n %}

 <p>&nbsp</p>
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">&laquo; {% trans "First" %}</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a></li>
    {% endif %}
    <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{% trans "Last" %} &raquo;</a></li>
    {% endif %}
</ul>

templates/post_delete.html
{% extends 'default.html' %}

{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}

{% block title %}
{% trans 'Delete post' %}
{% endblock title  %}

{% block content %}

<div class="form-group" style="margin-bottom: 25px; width: 800px; margin-left: 25px">
    <p>&nbsp</p>
    <h2 align="center" style="color: #000000"><b>{% trans 'Delete post' %}</b></h2>
<hr>
<div align="center" class="form-group" style="margin-bottom: 25px">
    <form action="" method="post" style="width: 700px">
        <h4 align="center" style="color: #000000"><b>{% trans 'Are you sure you want to delete?' %}</h4></b><h6></h6><i style="color: #0b1ef5"> {{ object.title }} </i> </h6>
        {% csrf_token %}
        <br>
        <br>
        <div align="center" style="margin-top:15px; margin-bottom: 15px">
            <input type="submit" value="{% trans 'Delete' %}" class="btn btn-outline-danger"/>
            <a href="{% url 'post_detail' object.id%}" class="btn btn-success">{% trans 'Cancel' %}</a>
        </div>
        <br><br>
    </form>
</div>

{% endblock content %}

templates/post_detail.html
{% extends 'default.html' %}

{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}

{% block title %}
{{ post.title|censor }}
{% endblock title %}

{% block content %}

<div class="form-group" style="margin-bottom: 25px; width: 700px; margin-left: 25px">
  <p>&nbsp</p>
  <h2>{{ OnePost.title|censor }}</h2>
  <p class="card-text"><small class="text-muted">{{ OnePost.post_time|format_time }} by {{ OnePost.author }}
    {% if OnePost.author.username == user.username %}
      <a href="{% url 'post_edit' OnePost.id %}">Edit post /</a>
      <a href="{% url 'post_delete' OnePost.id %}">Delete post</a>
    {% endif %}
  </small></p>
  <p>{{ OnePost.content|censor|safe }}</p>
</div>

<p>&nbsp</p>
<hr>

<div class="form-group" style="margin-bottom: 25px; width: 700px; margin-left: 25px">
  <h4>Comment{{ comments.count|pluralize }} ( {{ comments.count }} )</h4>
  <br>
  {% if user.is_authenticated %} 
      {% if OnePost.author.username != user.username %}
      <div style="text-align: left">
        <form action="" method="post" style="width: 700px">
            <style>
                label {font-weight:bold}
            </style>
            {% csrf_token %}
            {{ comment_form.as_table }}
            <br>
            <input class="btn btn-primary" type="submit" value="{% trans 'Send' %}">
        </form>
      </div>
      {% endif %}
  {% else %}
  <p>{% trans "You need to be" %} <a href='/accounts/login/'>{% trans "logged in" %}</a> {% trans "to see or leave comments" %}</p>
  {% endif %}

  {% if user.username == OnePost.author.username %}
      {% if comments %}
            {% for comment in comments %}
                      <tr>
                      <td><b><i>{{ comment.author__username }}</i></b></td>
                      <td><b><i>| {{ comment.post_time|format_time }} </i></b></td>
                      <td><b><i>| {{ comment.status }}</i></b></td>
                              <p>{{ comment.content }}</p>
            {% endfor %}
      {% else %}
      <p>{% trans "No comments yet" %}</p>
      {% endif %}
  {% else %}
  <p>{% trans "You are not authorized to see comments of other users" %}</p>
  {% endif %}
      
  <!-- {% if user.username != OnePost.author.username %} # Если комментарии всех пользователей открыты для всех
      {% if comments %}
        {% for comment in comments %}
                  {% if comment.status %}
                    <tr>
                    <td><b><i>{{ comment.author__username }}</i></b></td>
                    <td><b><i>| {{ comment.post_time|format_time }} </i></b></td>
                            <p>{{ comment.content }}</p>
                  {% endif %}
        {% endfor %}
      {% else %}
      <p>{% trans "No comments yet" %}</p>
      {% endif %}
  {% endif %} -->
     
  <br>

  {% if 'search' in request.path %}
  <p align="center"><a href="{% url 'post_search' %}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 {% trans "Back to Search" %}</a></p>
  {% elif 'myposts' in request.path %}
  <p align="center"><a href="{% url 'mypost_list' %}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 {% trans "Back to My Posts" %}</a></p>
  {% elif 'posts' in request.path %}
  <p align="center"><a href="{% url 'post_list' %}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 {%trans "Back to Posts" %}</a></p>
  {% else %}
  <p align="center"><a href="{% url 'home' %}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 {% trans "Back to Home" %}</a></p>
  {%endif%}

</div>

{% endblock content %}

templates/post_edit.html
{% extends 'default.html' %}

{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}

{% block title %}
{% trans "Edit a post" %}
{% endblock title  %}

{% block content %}


<div class="form-group" style="margin-bottom: 25px; width: 700px; margin-left: 25px">
    <p>&nbsp</p>
    <h2 align="left" style="color: #000000"><b>{% trans "Edit a post" %}</b></h2>

    <div class="form-group" style="margin-bottom: 25px">
        <form action="" method="post" style="width: 800px">
            <style>
                .error { color: red }
                .errorlist li { color: red }
                label { font-weight: bold }
                input { margin-top: 20px; margin-bottom: 20px }
            </style>
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.media }}
            {{ form.as_table }}
            
            <div align="left" style="margin-top:15px; margin-bottom: 15px">
                <input type="submit" value="{% trans 'Save' %}" class="btn btn-primary"/>
                <a href="{% url 'post_detail' object.id %}" class="btn btn-outline-danger">{% trans 'Cancel' %}</a>
            </div>
        </form>
    <hr>
    </div>
</div>

{% endblock content %}

templates/post_list.html
{% extends 'default.html' %}

{% load static %}
{% load i18n %}
{% load custom_tags %}
{% load custom_filters %}

{% block title %}
{% trans "All posts" %}
{% endblock title %}


{% block content %}
<h1><b>{% trans "All posts" %}</b></h1>

{% for post in posts %}
<div class="card">
  {% for category in post.category.all %}  
  <h6 class="card-header"><em>Category: {{ category }}</em></h6>
  {% endfor %}
  <div class="card-body">
    <h4 class="card-title">{{ post.title|censor|safe }}</h4>
    <p class="card-text">{{ post.preview|censor|safe }}</p>
    <p class="card-text"><small class="text-muted">{{ post.post_time|format_time }} by {{ post.author }}</small></p>
    <a href="{% url 'post_detail' post.id %}" class="btn btn-primary">Read more</a>
  </div>
</div>

{% endfor %}
<p>&nbsp</p>
{% include 'pagination.html' %}

{% endblock content %}

templates/post_search.html
{% extends 'default.html' %}

{% load static %}
{% load i18n %}
{% load custom_tags %}
{% load custom_filters %}

{% block title %}
{% trans 'Post Search' %}
{% endblock title %}

{% block content %}


<style>
    .search-form {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        margin: 20px;
    }

    .search-form label {
        margin-right: 10px;
        font-weight: bold;
    }

    .search-form input, .search-form select {
        margin-right: 10px;
        padding: 5px;
    }

    .search-result {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        align-items: flex-start;
        margin: 20px;
    }

    .search-result .card {
        width: 30%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid gray;
        box-shadow: 2px 2px 5px gray;
    }

    .search-result .card a {
        text-decoration: none;
        color: black;
    }

    .search-result .card a:hover {
        text-decoration: underline;
    }
</style>

<h1 align="left" style="color: #333333"><b>Поиск объявлений</b></h1>
<hr>

<form action="" method="get" class="search-form">
    {{ filterset.form.non_field_errors }}
    {% for field in filterset.form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
    {% endfor %}
    <div align="center" style="margin-top:15px; margin-bottom: 15px">
        <input type="submit" class="btn btn-primary" value="{% trans 'Search' %}"/>
    </div>
    
</form>

{% if Post_search %}

    <hr>
    <div class="search-result">
        {% for post in Post_search %}
            <div class="card" style="display: inline-block; height: 120px; width: 1000px; margin: 10px; padding: 20px">
                <a href="{% url 'post_detail_search' post.id %}"><h3>{{ post.title|censor }}</h3></a>
                {% for post_category in post.postcategory_set.all %}
                <p class="card-text"><small class="text-muted">{% trans 'Posted' %} by <b>{{ post.author }}</b> {% trans 'in' %} <b>"{{ post_category.category.name }}"</b>.</small></p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% else %}
    <h2><b>К сожалению, по Вашему запросу ничего не найдено :(</b></h2>
{% endif %}
<p>&nbsp</p>
{% include 'pagination.html' %}

{% endblock content %}

templates/reply_on_comment.html
{% extends 'default.html' %}

{% load custom_filters %}

{% block title %}
Ответ на отклик
{% endblock title  %}


{% block content %}
    <h1 align="left" style="color: #333333"><b>Ответ на отклик к посту <em>"{{Comment.commentpost}}"</em></b></h1>
    <hr>
    <div align="left" style=" box-shadow: 0 0 10px 1px #330000; border-radius:20px; width: 800px; margin-left:20px; padding: 15px; background: linear-gradient(245deg,#B6C1D4,#92F1D5)">
        <figure>
          <blockquote class="blockquote">
            <p>{{ Reply.text }}</p>
          </blockquote>
          <figcaption class="blockquote-footer">
            Отклик от <cite title="Source Title">{{ Comment.author }}</cite>, {{ Comment.post_time|date:"d.m.Y" }} {{Comment.post_time|date:"H:i"}}
          </figcaption>
        </figure>
        <form method="post">
            {% csrf_token %}
            <input
                    id="response_text"
                    name="response_text"
                    class="form-control"
                    placeholder="Напечатайте Ваш ответ на отклик здесь...">

            <br>
            <input type="hidden" name="Reply_id" value="{{ Reply.id }}" />
            <button name="action" value="send_reply" style="text-align:right; font-size: 12px" class="btn btn-success">Отправить ответ</button>
        </form>
    </div>
{% endblock content %}

templates/usercomments.html
{% extends 'default.html' %}

{% load static %}
{% load custom_filters %}
{% load i18n %}

{% block title %}
{% trans "User Comments to My Posts" %}
{% endblock title %}

{% block content %}

<div class="form-group" style="margin-bottom: 25px; width: 700px; margin-left: 25px">
    <p>&nbsp</p>
    <h3 align="left" style="color: #000000"><b>{% trans 'User Comments for Approval' %}</b></h3>
    <hr>

    {% if usercomments %}
    <div align="center" class="form-group" style="margin-bottom: 25px;">

        <form action="" method="get" style="width: 800px; text-align: left;">
            <style>
                label { font-weight: bold } 
                input { margin-bottom: 15px }
            </style>

           {{ filterset.form.as_p }}

            <div align="left" style="margin-top:15px; margin-bottom: 15px">
                <input type="submit" value="{% trans 'Search' %}" class="btn btn-primary"/>
            </div>
       </form>
    <hr>
    </div>

    <table style="margin-right: auto; margin-right: auto;">
        {% for comment in usercomments %}
            <td style="text-align: justify">
            <!-- <a href="http://127.0.0.1:8000/post/{{ comment.post.id }}" style="text-decoration: none; color: #778899;">{{ comment.post.title }}</a> -->
            <p style="text-align: justify"><b>Comment by: </b>{{ comment.author }}
            | {{ comment.post_time|format_time }}
            <br>
                <i><b>Content: </b><a href="http://127.0.0.1:8000/posts/{{ comment.post.id }}" style="text-decoration: none; color: #778899;">{{ comment.content }}</a></i></p>
            
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" value='{{ comment.id }}' name="comment">
                {% if not comment.status %}
                    <input type="submit" value="{% trans 'Accept' %}" class="btn btn-success"/>
                {% else %}
                    <input type="submit" value="{% trans 'Reject' %}" class="btn btn-danger"/>
                {% endif %}
            </form>
        {% endfor %}
    </table>
{% else %}
<h3>No comments</h3>

{% endif %}

{% if usercomments %}
{% include 'pagination.html' %}
{% endif %}

{% endblock content %}